### ISSUE TITLE
VS Code Prework Missing Example

### ISSUE THREAD

**Issue by asejdina** [south-bend-code-school/intro-to-web-dev#13]
In this section, there appears to be a missing image or example that compares a Plain Text Editor to VS Code. We either need to put that info in there or remove that section. 
<img width="837" alt="Screen Shot 2020-12-16 at 9 45 03 AM" src="https://user-images.githubusercontent.com/6006108/102363404-60aabd00-3f83-11eb-9d78-59b5bd5fd976.png">

**Comment by cfreder2** [comment]
fixed
